FROM nvidia/cuda:12.2.0-devel-ubuntu20.04

# Non-interactive installs
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=US/Pacific

# Set timezone before installing tzdata
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Install system dependencies
RUN apt-get update --fix-missing && \
    apt-get install -y --no-install-recommends \
    tzdata \
    libgtk2.0-dev wget bzip2 ca-certificates curl git vim tmux \
    g++ gcc build-essential cmake checkinstall gfortran \
    libjpeg8-dev libtiff5-dev pkg-config yasm libavcodec-dev \
    libavformat-dev libswscale-dev libdc1394-22-dev libxine2-dev \
    libv4l-dev qt5-default libtbb-dev libatlas-base-dev libfaac-dev \
    libmp3lame-dev libtheora-dev libvorbis-dev libxvidcore-dev \
    libopencore-amrnb-dev libopencore-amrwb-dev x264 v4l-utils \
    libprotobuf-dev protobuf-compiler libgoogle-glog-dev \
    libgflags-dev libgphoto2-dev libhdf5-dev doxygen libflann-dev \
    libboost-all-dev proj-data libproj-dev libyaml-cpp-dev \
    cmake-curses-gui libzmq3-dev freeglut3-dev && \
    rm -rf /var/lib/apt/lists/*

# Build and install pybind11
RUN git clone https://github.com/pybind/pybind11 /pybind11 && \
    cd /pybind11 && git checkout v2.10.0 && \
    mkdir build && cd build && \
    cmake .. -DCMAKE_BUILD_TYPE=Release -DPYBIND11_INSTALL=ON -DPYBIND11_TEST=OFF && \
    make -j$(nproc) && make install

# Build and install Eigen
RUN wget -q https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.tar.gz && \
    tar xvzf eigen-3.4.0.tar.gz && cd eigen-3.4.0 && \
    mkdir build && cd build && cmake .. && make install && \
    rm -rf /eigen-3.4.0 eigen-3.4.0.tar.gz

# Use bash login shell for Conda initialization
SHELL ["/bin/bash", "--login", "-c"]

# Install Miniconda and create 'my' environment
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O /miniconda.sh && \
    bash /miniconda.sh -b -p /opt/conda && rm /miniconda.sh && \
    /opt/conda/bin/conda update -n base -c defaults conda -y && \
    /opt/conda/bin/conda create -n my python=3.8 -y

# Add both base conda and 'my' env to PATH
ENV PATH=/opt/conda/bin:/opt/conda/envs/my/bin:$PATH
RUN conda init bash

# Install PyTorch & related libraries in 'my' 
# check this page for version compatibility: https://pytorch.org/get-started/previous-versions/
RUN conda run -n my pip install \
    torch==2.2.2+cu121 \
    torchvision==0.17.2+cu121 \
    torchaudio==2.2.2+cu121 \
    --extra-index-url https://download.pytorch.org/whl/cu121 && \
    conda run -n my pip install "git+https://github.com/facebookresearch/pytorch3d.git@stable" && \
    conda run -n my pip install \
    scipy joblib scikit-learn ruamel.yaml trimesh pyyaml \
    opencv-python imageio open3d transformations warp-lang \
    einops kornia pyrender

# Build & install Kaolin
RUN git clone --recursive https://github.com/NVIDIAGameWorks/kaolin /kaolin && \
    conda run -n my pip install "Cython>=0.29.37" && \
    cd /kaolin && conda run -n my python setup.py develop

# Build & install nvdiffrast
RUN git clone https://github.com/NVlabs/nvdiffrast /nvdiffrast && \
    cd /nvdiffrast && conda run -n my pip install .

# Additional Python packages
RUN conda run -n my pip install \
    scikit-image meshcat webdataset omegaconf pypng roma seaborn \
    opencv-contrib-python openpyxl wandb imgaug Ninja xlsxwriter \
    timm albumentations xatlas rtree nodejs jupyterlab objaverse \
    g4f ultralytics==8.0.120 pycocotools videoio numba && \
    conda run -n my conda install -y -c anaconda h5py

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
CMD ["bash"]

# Fix /bin/sh link
RUN ln -sf /bin/bash /bin/sh